# Generated by Django 3.0 on 2020-12-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('IDAct', models.IntegerField(primary_key=True, serialize=False)),
                ('NameAct', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('IDBuilding', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NameBuilding', models.CharField(max_length=50)),
                ('Floor', models.IntegerField()),
                ('Room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('IDBooking', models.AutoField(primary_key=True, serialize=False)),
                ('NameBooking', models.CharField(max_length=30)),
                ('DateBook', models.DateField()),
                ('TimeStart', models.TimeField()),
                ('TimeStop', models.TimeField()),
                ('People', models.IntegerField()),
                ('Status', models.BooleanField(default=False)),
                ('IDAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key.Act')),
                ('IDBuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key.Building')),
            ],
        ),
    ]
